/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domosym.gui;

import Model.domosym.DomoSymApplicationController;
import Model.domosym.Simulazione;
import backyard.gui.*;
import model.backyard.tipoUtente;
import model.backyard.ScenarioSimulazione;
import model.backyard.UserInfo;
import model.backyard.InfoScenario;
import model.backyard.BackYardApplicationController;
import java.awt.CardLayout;
import java.awt.Container;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * Questa classe fa da GUI Controller per le operazioni di Gestire Scenari di
 * Simulazione. Il tag @OPERATION indica dove bisogna inserire le invocazioni
 * alle operazioni di sistema.
 *
 * @author picardi
 */
public class DomoSym extends javax.swing.JFrame {

	private static Container mainPane;

	private DefaultListModel<InfoScenario> scenariListModel;
	private SimPanel scenarioPanel;
	private UserInfo uInfo;        

	/**
	 * Creates new form BackYardMainWindow
	 */
	public DomoSym() {
                super("DomoSym");
		initComponents();
		// Inizializzazione elementi di interfaccia
		scenariListModel = new DefaultListModel<>();
		this.scenariList.setModel(scenariListModel);		
		scenarioPanel = new SimPanel(this);
		getContentPane().add(scenarioPanel, "DettagliScenario");
		mainPane = getContentPane();                
	}

	public static Container getMainPane() {
		return mainPane;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPanel = new javax.swing.JPanel();
        javax.swing.JPanel userInnerP = new javax.swing.JPanel();
        javax.swing.JLabel usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        usernameInnerSP = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        elencoScenariPanel = new javax.swing.JPanel();
        javax.swing.JPanel elencoScenariCPan = new javax.swing.JPanel();
        javax.swing.JScrollPane scenariListScroll = new javax.swing.JScrollPane();
        scenariList = new javax.swing.JList();
        javax.swing.JLabel elencoScenariLabel = new javax.swing.JLabel();
        javax.swing.JPanel elencoScenariSP = new javax.swing.JPanel();
        nuovoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        userPanel.setLayout(flowLayout1);

        userInnerP.setLayout(new java.awt.BorderLayout());

        usernameLabel.setText("Inserisci il tuo identificativo e e premi Ok per iniziare:");
        userInnerP.add(usernameLabel, java.awt.BorderLayout.NORTH);
        userInnerP.add(usernameField, java.awt.BorderLayout.CENTER);

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        usernameInnerSP.add(okButton);

        userInnerP.add(usernameInnerSP, java.awt.BorderLayout.SOUTH);

        userPanel.add(userInnerP);

        getContentPane().add(userPanel, "User");

        elencoScenariPanel.setLayout(new java.awt.BorderLayout());

        elencoScenariCPan.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4))));
        elencoScenariCPan.setLayout(new java.awt.BorderLayout());

        scenariList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scenariList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                scenariListValueChanged(evt);
            }
        });
        scenariListScroll.setViewportView(scenariList);

        elencoScenariCPan.add(scenariListScroll, java.awt.BorderLayout.CENTER);

        elencoScenariLabel.setText("Scenari di simulazione disponibili per la simulazione:");
        elencoScenariCPan.add(elencoScenariLabel, java.awt.BorderLayout.NORTH);

        elencoScenariPanel.add(elencoScenariCPan, java.awt.BorderLayout.CENTER);

        nuovoButton.setText("Imposta Simulazione");
        nuovoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuovoButtonActionPerformed(evt);
            }
        });
        elencoScenariSP.add(nuovoButton);

        elencoScenariPanel.add(elencoScenariSP, java.awt.BorderLayout.SOUTH);

        getContentPane().add(elencoScenariPanel, "ElencoScenari");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
		// Ottiene il testo inserito dall'utente
		String nomeUtente = this.usernameField.getText().trim();
		if (nomeUtente.length() > 0) { // Il nome utente e' non vuoto
			/* @MODELINTERACTION crea un oggetto UserInfo con il nome specificato e tipo=TECNICO
			 * variabili id e password al momento non usate (non c'e' un vero login ne' un
			 * DB degli utenti - se ci fosse qui dovremmo collegarci e reperire le informazioni
			 * (id e tipo) a partire da username e password. 
			 * E' dunque atteso in UserInfo un costruttore:
			 * UserInfo(String, UserInfo.TipoUtente)
			 * (modificare in caso si sia usato un modo diverso x rappresentare il tipo)
			 */
			// @EXAMPLES T2&T3
			uInfo = new UserInfo(nomeUtente, tipoUtente.INQUILINO);
                        DomoSymApplicationController app = new DomoSymApplicationController(uInfo);

			/* @OPERATIONottieniScenariDiSimulazione
			 */
			// @EXAMPLES T2/T3:
			//ArrayList<InfoScenario> scenari = BackYardCtrl.ottieniElencoScenari(uInfo);
			ArrayList<InfoScenario> scenari = new ArrayList<>();
                        try {
                            scenari = DomoSymApplicationController.appCtrl.OttieniScenariDiSimulazione(uInfo);
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(this, "Errore nella connessione col DB", "Errore", JOptionPane.ERROR_MESSAGE);
                        }

			/* Inizializzazione della lista di scenari
			 * @MODELINTERACTION la visualizzazione degli oggetti nell'elenco è basata sul metodo
			 * toString degli oggetti stessi. Implementarlo appropriatamente
			 */
			this.aggiornaElencoScenari(scenari);

			// Mostra il pannello con l'elenco degli scenari
			((CardLayout) this.getContentPane().getLayout()).show(this.getContentPane(), "ElencoScenari");

		} else { // L'utente non ha inserito alcun testo
			JOptionPane.showMessageDialog(this, "Nome utente non valido", "Errore", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_okButtonActionPerformed

    private void scenariListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_scenariListValueChanged
		
    }//GEN-LAST:event_scenariListValueChanged

    private void nuovoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuovoButtonActionPerformed
		// Ottiene l'oggetto InfoScenario selezionato nell'elenco
		InfoScenario scInfo = (InfoScenario) scenariList.getSelectedValue();
		/* @OPERATIONapriScenario
		 */

		// @EXAMPLES T2/T3:
		// ScenarioSimulazione scenario = BackYardCtrl.apriScenario(scInfo);
		Simulazione sim= null;
                try {
                    sim = DomoSymApplicationController.appCtrl.apriSimulazione(scInfo);
                } catch (Exception ex) {
                    Logger.getLogger(BackYard.class.getName()).log(Level.SEVERE, null, ex);
                }

		// inizializza la vista dello scenario
		scenarioPanel.setup(sim);
		// mostra il pannello dello scenario
		((CardLayout) this.getContentPane().getLayout()).show(this.getContentPane(), "DettagliScenario");
    }//GEN-LAST:event_nuovoButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DomoSym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DomoSym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DomoSym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DomoSym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				/* @MODELINTERACTION qui va inizializzato il GRASP controller principale, su cui
				 * invocare le operazioni di "Gestire Scenari". 
				 * E' atteso in BackYardApplicationController un metodo:
				 * - initApplication(): void
				 */
				BackYardApplicationController.initApplication();

				// crea la vista principale e la mostra
				DomoSym mainView = new DomoSym();
				mainView.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel elencoScenariPanel;
    private javax.swing.JButton nuovoButton;
    private javax.swing.JButton okButton;
    private javax.swing.JList scenariList;
    private javax.swing.JPanel userPanel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JPanel usernameInnerSP;
    // End of variables declaration//GEN-END:variables

	private void aggiornaElencoScenari(ArrayList<InfoScenario> scenari) {
		this.scenariListModel.removeAllElements();
		for (InfoScenario sc : scenari) {
			this.scenariListModel.addElement(sc);                        
                       
		}

		this.scenariList.clearSelection();
	}

	void chiudiScenario(java.awt.event.ActionEvent evt) {
		((CardLayout) this.getContentPane().getLayout()).show(this.getContentPane(), "ElencoScenari");
		
		this.okButtonActionPerformed(evt);
	}
}
