/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domosym.gui;

import Model.domosym.*;
import backyard.gui.*;
import model.backyard.Alloggio;
import model.backyard.ScenarioSimulazione;
import model.backyard.UserInfo;
import model.backyard.InfoScenario;
import model.backyard.Importabile;
import model.backyard.Stanza;
import model.backyard.DispositivoIntelligente;
import model.backyard.BackYardApplicationController;
import model.backyard.Contesto;
import model.backyard.Piano;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import model.backyard.Evento;

/**
 *
 * @author picardi
 */
public class SimPanel extends javax.swing.JPanel {

	private Simulazione mySim; //memorizza il GRASP controller delle operazioni che gestirà
	private DomoSym owner;
	private Alloggio planimetria;
	private DefaultListModel<Programma> progListModel;
	private DefaultListModel<ComandoProgramma> comListModel;
	private DefaultComboBoxModel<DispositivoIntelligente> dispositiviComboModel;	
	private String nomeContesto;

	/**
	 * Creates new form ScenarioPanel
	 */
	public SimPanel(DomoSym by) {
		owner = by;
		initComponents();
		progListModel = new DefaultListModel<>();
		this.programmiList.setModel(progListModel);
		comListModel = new DefaultListModel<>();
		this.comandiList.setModel(comListModel);
		dispositiviComboModel = new DefaultComboBoxModel<>();
		
	}

	/* Inizializza questo pannello con un dato Scenario di Simulazione
	 *
	 */
	public void setup(Simulazione sim) {
		this.titleLabel.setText("Simulazione di: " + sim.getScenario().getNome());
		mySim = sim;

		ArrayList<Programma> prog = mySim.ottieniElencoProgrammi();	
		simulazioneTabbed.setSelectedIndex(0);

		aggiornaElencoProgrammi(prog);
		//aggiornaElencoDispositivi(dispositivi);

		// All'inizio nessun piano è selezionato
		((CardLayout) this.programmaP.getLayout()).show(programmaP, "Blank");
		this.eliminaPianoButton.setEnabled(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simulazioneTabbed = new javax.swing.JTabbedPane();
        programmaPanel = new javax.swing.JPanel();
        javax.swing.JSplitPane planimetriaSplit = new javax.swing.JSplitPane();
        elencoProgrammi = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        programmiList = new javax.swing.JList();
        javax.swing.JPanel pianiSP = new javax.swing.JPanel();
        nuovoPianoButton = new javax.swing.JButton();
        eliminaPianoButton = new javax.swing.JButton();
        programmaP = new javax.swing.JPanel();
        blankPanel = new javax.swing.JPanel();
        editProgrammaP = new javax.swing.JPanel();
        javax.swing.JPanel datiProgramma = new javax.swing.JPanel();
        datiLabel = new javax.swing.JLabel();
        javax.swing.JPanel datiProgrammaEP = new javax.swing.JPanel();
        attivaButton = new javax.swing.JButton();
        modificaDatiButton = new javax.swing.JButton();
        javax.swing.JPanel elencoComandi = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        comandiList = new javax.swing.JList();
        javax.swing.JPanel comandiSP = new javax.swing.JPanel();
        nuovaStanzaButton = new javax.swing.JButton();
        eliminaStanzaButton = new javax.swing.JButton();
        modificaComandoButton = new javax.swing.JButton();
        iscrizioniPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        javax.swing.JPanel simulazioneTitle = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        javax.swing.JPanel scenarioTitleEP = new javax.swing.JPanel();
        chiudiButton = new javax.swing.JButton();
        salvaButton = new javax.swing.JButton();
        scenarioSP = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        importaButton = new javax.swing.JButton();
        risorseButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        simulazioneTabbed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                simulazioneTabbedStateChanged(evt);
            }
        });

        programmaPanel.setLayout(new java.awt.BorderLayout());

        planimetriaSplit.setDividerLocation(250);

        elencoProgrammi.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2))));
        elencoProgrammi.setLayout(new java.awt.BorderLayout());

        programmiList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        programmiList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                programmiListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(programmiList);

        elencoProgrammi.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        nuovoPianoButton.setLabel("Nuovo...");
        nuovoPianoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuovoPianoButtonActionPerformed(evt);
            }
        });
        pianiSP.add(nuovoPianoButton);

        eliminaPianoButton.setText("Elimina");
        eliminaPianoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaPianoButtonActionPerformed(evt);
            }
        });
        pianiSP.add(eliminaPianoButton);

        elencoProgrammi.add(pianiSP, java.awt.BorderLayout.SOUTH);

        planimetriaSplit.setLeftComponent(elencoProgrammi);

        programmaP.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2))));
        programmaP.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout blankPanelLayout = new javax.swing.GroupLayout(blankPanel);
        blankPanel.setLayout(blankPanelLayout);
        blankPanelLayout.setHorizontalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        blankPanelLayout.setVerticalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        programmaP.add(blankPanel, "Blank");

        editProgrammaP.setLayout(new java.awt.BorderLayout());

        datiProgramma.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        datiProgramma.setLayout(new java.awt.BorderLayout());

        datiLabel.setText("Scenario corrente: NOME");
        datiProgramma.add(datiLabel, java.awt.BorderLayout.WEST);

        attivaButton.setText("Attiva");
        attivaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attivaButtonActionPerformed(evt);
            }
        });
        datiProgrammaEP.add(attivaButton);

        modificaDatiButton.setLabel("Modifica...");
        modificaDatiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaDatiButtonActionPerformed(evt);
            }
        });
        datiProgrammaEP.add(modificaDatiButton);

        datiProgramma.add(datiProgrammaEP, java.awt.BorderLayout.EAST);

        editProgrammaP.add(datiProgramma, java.awt.BorderLayout.NORTH);

        elencoComandi.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4))));
        elencoComandi.setLayout(new java.awt.BorderLayout());

        comandiList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        comandiList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                comandiListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(comandiList);

        elencoComandi.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        nuovaStanzaButton.setText("Crea Comando");
        nuovaStanzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuovaStanzaButtonActionPerformed(evt);
            }
        });
        comandiSP.add(nuovaStanzaButton);

        eliminaStanzaButton.setText("Elimina");
        eliminaStanzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaStanzaButtonActionPerformed(evt);
            }
        });
        comandiSP.add(eliminaStanzaButton);

        modificaComandoButton.setText("Modifica...");
        modificaComandoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaComandoButtonActionPerformed(evt);
            }
        });
        comandiSP.add(modificaComandoButton);

        elencoComandi.add(comandiSP, java.awt.BorderLayout.SOUTH);

        editProgrammaP.add(elencoComandi, java.awt.BorderLayout.CENTER);

        programmaP.add(editProgrammaP, "EditPiano");

        planimetriaSplit.setRightComponent(programmaP);

        programmaPanel.add(planimetriaSplit, java.awt.BorderLayout.CENTER);

        simulazioneTabbed.addTab("Programmi", programmaPanel);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("Nome:");

        jLabel2.setText("Collocazione:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout iscrizioniPanelLayout = new javax.swing.GroupLayout(iscrizioniPanel);
        iscrizioniPanel.setLayout(iscrizioniPanelLayout);
        iscrizioniPanelLayout.setHorizontalGroup(
            iscrizioniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iscrizioniPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        iscrizioniPanelLayout.setVerticalGroup(
            iscrizioniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        simulazioneTabbed.addTab("Iscrizioni", iscrizioniPanel);

        add(simulazioneTabbed, java.awt.BorderLayout.CENTER);

        simulazioneTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        simulazioneTitle.setLayout(new java.awt.BorderLayout());

        titleLabel.setText("Simulazion di: NOME");
        simulazioneTitle.add(titleLabel, java.awt.BorderLayout.WEST);

        chiudiButton.setText("Chiudi");
        chiudiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiudiButtonActionPerformed(evt);
            }
        });
        scenarioTitleEP.add(chiudiButton);

        salvaButton.setText("Salva");
        salvaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaButtonActionPerformed(evt);
            }
        });
        scenarioTitleEP.add(salvaButton);

        simulazioneTitle.add(scenarioTitleEP, java.awt.BorderLayout.EAST);

        add(simulazioneTitle, java.awt.BorderLayout.NORTH);

        jButton1.setText("Iscriviti!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        scenarioSP.add(jButton1);

        importaButton.setText("Imposta Avviso");
        importaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importaButtonActionPerformed(evt);
            }
        });
        scenarioSP.add(importaButton);

        risorseButton.setText("Imposta Allarme");
        risorseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                risorseButtonActionPerformed(evt);
            }
        });
        scenarioSP.add(risorseButton);

        add(scenarioSP, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void chiudiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiudiButtonActionPerformed
		/* @MODELINTERACTION per verificare se può chiudere tranquillamente,
		 * la vista chiama sull'oggetto ScenarioSimulazione il seguente metodo:
		 * - isSalvato(): boolean
		 * che restituisce il valore della variabile di istanza 'salvato'
		 */
		int option = JOptionPane.YES_OPTION;
		if (!mySim.getSalvato()) {
			option = JOptionPane.showConfirmDialog(this.owner, "Sicuro di voler chiudere? \nCi sono informazioni non salvate.",
				"Attenzione", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
		}
		if (option == JOptionPane.YES_OPTION) // se era gia' salvato o se l'utente ha detto si'
		{
			//owner.chiudiScenario(evt);
		}
    }//GEN-LAST:event_chiudiButtonActionPerformed

    private void modificaDatiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaDatiButtonActionPerformed
		// Ottiene il Piano selezionato, di cui vanno modificati i dati
		Programma p = (Programma) this.programmiList.getSelectedValue();

		// Chiede il  nome e il livello (e' possibile che l'utente prema cancel rinunciando all'operazione)
		/* @MODELINTERACTION per inizializzare i dati della dialog di richiesta,
		 * la vista richiama sull'oggetto Piano i seguenti metodi 
		 * - getNome(): String
		 * - getLivello(): int
		 */
		String nome = p.getNome();
		DatiProgrammaDialog dia = new DatiProgrammaDialog(this.owner);
		dia.setNome(nome);	
                dia.setTipo(!p.isGenerico());
                dia.setRatioOff();
		dia.setVisible(true);

		if (dia.getValue() == JOptionPane.OK_OPTION) { // L'utente ha premuto Ok

			// Ottiene il nome inserito
			nome = dia.getNome();
			if (nome.length() > 0) { // Il nome inserito e' non vuoto
				/* @OPERATIONmodificaPiano
				 * in base a come si è gestito il caso di nome o livello non valido, bisogna o catturare
				 * l'eccezione o verificare il valore restituito dall'operazione. In ogni
				 * caso si può mostrare una message dialog analoga a quella che qui viene visualizzata quando l'utente
				 * non inserisce NESSUN NOME.
				 */

				// @EXAMPLES T2/T3:
				// Piano p = BackYardCtrl.modificaPiano(piano, nome, livello);
				boolean modified= mySim.modificaNomeProgramma(p, nome);
                                
                                

				if (modified) // Alternative: se NON viene lanciata alcuna eccezione, o se il piano restituito è NON null
				{
					/* @MODELINTERACTION la vista richiama sull'oggetto ScenarioSimulazione
					 * il seguente metodo necessario al proprio aggiornamento 
					 * - getPiani(): ArrayList<Piano>
					 */
					ArrayList<Programma> prog = this.mySim.ottieniElencoProgrammi();
					this.aggiornaElencoProgrammi(prog);

					// Seleziona il piano appema modificato
					this.programmiList.setSelectedValue(prog, true);
				} else { // Alternative: se viene lanciata una eccezione o se il piano restituito è null
					JOptionPane.showMessageDialog(this, "Nome del programma non disponibile", "Errore", JOptionPane.ERROR_MESSAGE);
				}

			} else { // Il nome inserito e' vuoto
				JOptionPane.showMessageDialog(this, "Nome programma non valido", "Errore", JOptionPane.ERROR_MESSAGE);
			}
		}
    }//GEN-LAST:event_modificaDatiButtonActionPerformed

    private void programmiListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_programmiListValueChanged
		if (!evt.getValueIsAdjusting()) {			
			int sel = programmiList.getSelectedIndex();
			this.eliminaPianoButton.setEnabled(sel >= 0);
			if (sel < 0) {
				((CardLayout) this.programmaP.getLayout()).show(programmaP, "Blank");
			} else { 				
				Programma p = (Programma) programmiList.getSelectedValue();
                                if(this.mySim.getSimula()!= null && this.mySim.getSimula().getNome().equals(p.getNome())){
                                    this.attivaButton.setText("Disattiva");  
                                }
                                else if(!p.isGenerico() ){
                                    this.attivaButton.setEnabled(true);
                                    this.attivaButton.setText("Attiva");   
                                }
                                else{
                                    this.attivaButton.setEnabled(false);
                                    this.attivaButton.setText("Attiva");
                                }                                
				ArrayList<ComandoProgramma> comandi = p.getComandi();
				String nome = p.getNome();

				// Imposta il lato destro della finestra in modo che visualizzi le informazioni del piano selezionato
				this.datiLabel.setText("Nome Programma: "+nome);
				aggiornaElencoComandi(comandi);

				// All'inizio nessuna stanza e' selezionata, quindi i pulsanti relativi sono disabilitati
				this.eliminaStanzaButton.setEnabled(false);
				this.modificaComandoButton.setEnabled(false);
                                
				

				// Mostra il pannello con le informazioni del piano selezionato
				((CardLayout) this.programmaP.getLayout()).show(programmaP, "EditPiano");
			}

		}
    }//GEN-LAST:event_programmiListValueChanged

    private void eliminaPianoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaPianoButtonActionPerformed
		// Ottiene oggetto selezionato nell'elenco
		Programma p = (Programma) programmiList.getSelectedValue();

		boolean eliminato = this.mySim.eliminaProgramma(p.getNome());                
		// Aggiornamento view
		if (eliminato) {
			/* @MODELINTERACTION la vista richiama sull'oggetto ScenarioSimulazione
			 * il seguente metodo necessario al proprio aggiornamento 
			 * - getPiani(): ArrayList<Piano>
			 */
			ArrayList<Programma> progs = mySim.ottieniElencoProgrammi();
			this.aggiornaElencoProgrammi(progs);
		} else {
			// Caso in cui il piano non è elimiminabile
			JOptionPane.showMessageDialog(this, "Non si può eliminare questo programma", "Errore", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_eliminaPianoButtonActionPerformed

    private void nuovoPianoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuovoPianoButtonActionPerformed
		// Chiede il  nome e il livello (e' possibile che l'utente prema cancel rinunciando all'operazione)
		DatiProgrammaDialog dia = new DatiProgrammaDialog(this.owner);
		dia.setVisible(true);

		if (dia.getValue() == JOptionPane.OK_OPTION) { // L'utente ha premuto Ok

			// Ottiene il nome inserito
			String nome = dia.getNome();

			// Ottiene il livello inserito
			boolean tipo = dia.getTipo();

			if (nome.length() > 0) { // Il nome inserito e' non vuoto
				/* @OPERATIONaggiungiPiano
				 * in base a come si è gestito il caso di nome o livello non valido, bisogna o catturare
				 * l'eccezione o verificare il valore restituito dall'operazione. In ogni
				 * caso si può mostrare una message dialog analoga a quella che qui viene visualizzata quando l'utente
				 * non inserisce NESSUN NOME.
				 */

				// @EXAMPLES T2/T3:
				// Piano p = BackYardCtrl.aggiungiPiano(nome, livello);
				Programma p= this.mySim.creaNuovoProgramma(nome, tipo);
                               

				if (p != null) // Alternativamente: se NON viene lanciata alcuna eccezione
				{
					/* @MODELINTERACTION la vista richiama sull'oggetto ScenarioSimulazione
					 * il seguente metodo necessario al proprio aggiornamento 
					 * - getPiani(): ArrayList<Piano>
					 */
					ArrayList<Programma> prog = mySim.ottieniElencoProgrammi();
					this.aggiornaElencoProgrammi(prog);;
				} else { // ALternativamente: se viene lanciata una eccezine
					JOptionPane.showMessageDialog(this, "Nome del programma non disponibile", "Errore", JOptionPane.ERROR_MESSAGE);
				}

			} else { // Il nome inserito e' vuoto
				JOptionPane.showMessageDialog(this, "Nome programma non valido", "Errore", JOptionPane.ERROR_MESSAGE);
			}
		}
    }//GEN-LAST:event_nuovoPianoButtonActionPerformed

    private void comandiListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_comandiListValueChanged
		if (!evt.getValueIsAdjusting()) {
			int sel = comandiList.getSelectedIndex();
			this.eliminaStanzaButton.setEnabled(sel >= 0);
			this.modificaComandoButton.setEnabled(sel >= 0);
		}
    }//GEN-LAST:event_comandiListValueChanged

    private void salvaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaButtonActionPerformed
		/* @MODELINTERACTION per verificare se c'e' qualcosa da salvare,
		 * la vista chiama sull'oggetto ScenarioSimulazione il seguente metodo:
		 * - isSalvato(): boolean
		 * che restituisce il valore della variabile di istanza 'salvato'
		 */
		if (mySim.getSalvato()) {
			JOptionPane.showMessageDialog(this.owner, "Nulla di nuovo da salvare.",
				"Informazione", JOptionPane.INFORMATION_MESSAGE);
		} else {
			/* @OPERATIONsalvaScenario
			 */
			// @EXAMPLES T2/T3:
			// BackYardCtrl.salvaScenario();
			DomoSymApplicationController.appCtrl.salvaSimulazione();
		}
    }//GEN-LAST:event_salvaButtonActionPerformed

    private void nuovaStanzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuovaStanzaButtonActionPerformed
		// Chiede il  nome (e' possibile che l'utente prema cancel rinunciando all'operazione)
		NomeComandoDialog dia = new NomeComandoDialog(this.owner);
		dia.setVisible(true);

		if (dia.getValue() == JOptionPane.OK_OPTION) { // L'utente ha premuto Ok

			// Ottiene il nome inserito
			String nome = dia.getNome();

			if (nome.length() > 0) { // Il nome inserito e' non vuoto

				// Determina il piano a cui aggiungere la stanza
				Programma p = (Programma) programmiList.getSelectedValue();
				
				/* @OPERATIONaggiungiStanza
				 * in base a come si è gestito il caso di nome non valido, bisogna o catturare
				 * l'eccezione o verificare il valore restituito dall'operazione. In ogni
				 * caso si può mostrare una message dialog analoga a quella che qui viene visualizzata quando l'utente
				 * non inserisce NESSUN NOME.
				 */

				// @EXAMPLES T2/T3:
				// Stanza s = BackYardCtrl.aggiungiStanza(piano, nome);
				ComandoProgramma com=mySim.creaNuovoComando(nome, p);
                               

				if (com != null) // Alternativamente: se NON viene lanciata alcuna eccezione
				{
					/* @MODELINTERACTION la vista richiama sull'oggetto Piano
					 * il seguente metodo necessario al proprio aggiornamento 
					 * - getStanze(): ArrayList<Stanza>
					 */
					ArrayList<ComandoProgramma> comandi = p.getComandi();
					this.aggiornaElencoComandi(comandi);
				} else { // ALternativamente: se viene lanciata una eccezione
					JOptionPane.showMessageDialog(this, "Nome non disponibile", "Errore", JOptionPane.ERROR_MESSAGE);
				}

			} else { // Il nome inserito e' vuoto
				JOptionPane.showMessageDialog(this, "Nome stanza non valido", "Errore", JOptionPane.ERROR_MESSAGE);
			}
		}
    }//GEN-LAST:event_nuovaStanzaButtonActionPerformed

    private void eliminaStanzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaStanzaButtonActionPerformed
		// Ottiene stanza selezionata nell'elenco
                Programma p = (Programma) programmiList.getSelectedValue();
		ComandoProgramma com = (ComandoProgramma) comandiList.getSelectedValue();

		/* @OPERATIONeliminaStanza
		 * in base a come si è gestito il caso di stanza che non si può eliminare, bisogna o catturare
		 * l'eccezione o verificare il valore restituito dall'operazione. Qui in caso di valore restituito
		 * pari a false (piano non eliminabile) viene visualizzato un messaggio di errore.		
		 */
		// @EXAMPLES T2/T3:
		// boolean eliminato = BackYardCtrl.eliminaStanza(s);		
		boolean eliminato = mySim.cancellaComando(com.getNome(), p);

		// Aggiornamento view
		if (eliminato) {
			/* @MODELINTERACTION la vista richiama sull'oggetto Piano
			 * attualmente selezionato
			 * il seguente metodo necessario al proprio aggiornamento 
			 * - getStanze(): ArrayList<Stanza>
			 */

			// Ottiene il piano selezionato			
			ArrayList<ComandoProgramma> comandi = p.getComandi();
			this.aggiornaElencoComandi(comandi);

		} else {
			// Caso in cui il piano non è elimiminabile
			JOptionPane.showMessageDialog(this, "Non si può eliminare questo comando", "Errore", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_eliminaStanzaButtonActionPerformed

    private void modificaComandoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaComandoButtonActionPerformed
		// Chiede il  nome (e' possibile che l'utente prema cancel rinunciando all'operazione)
                ComandoProgramma com = (ComandoProgramma) comandiList.getSelectedValue();
		ModificaComandoDialog dia = new ModificaComandoDialog(this.owner);
                dia.setNome(com.getNome());
                dia.setAzione(com.getAzioneComando());
                ArrayList<Evento> eventi = this.mySim.ottieniListaEventi();
                ArrayList<AzioneComando> azioni = this.mySim.getAzioniComandoDisponibili();
                dia.setAzioni(azioni);                
                dia.setEventi(eventi);
                if(com.getAzioneComando()!= null){
                    dia.setDurata(com.getAzioneComando().getDurata());                
                    if(com.getAzioneComando() instanceof Evento){
                        dia.setEvento((Evento)com.getCondizione());                    
                    }
                    else{
                        dia.setOrario(((Orario)com.getCondizione()).toString());
                    }
                }
		dia.setVisible(true);

		if (dia.getValue() == JOptionPane.OK_OPTION) { // L'utente ha premuto Ok

			// Ottiene il nome inserito
			String nome = dia.getNome();
                        //Ottengo l'azione
                        AzioneComando az = dia.getAzione();
                        //Ottengo la durata
                        int durata = dia.getDurata();
                        //Ottengo la condizione di attivazione
                        Orario ora= dia.getOrario();
                        Evento ev = dia.getEvento();
                        
			if (nome.length() > 0 && az != null && durata >0 && ora != null && (ora.validate() || ev!= null)) {                                
                                                            
				boolean modificato = mySim.cambiaNomeComando(com, nome);
                                boolean modAzione = false;
                                
                                if(az instanceof ProgrammaGenerico) modAzione= mySim.aggiungiSottoprogramma(com,(ProgrammaGenerico)az);
                                else modAzione= mySim.impostaAzione(com, az);
                                
                                if (modificato) {
                                    if(modAzione){
                                        mySim.impostaDurata(com, durata);      
                                        if(dia.isOraro())
                                            mySim.impostaCondizioneAttivazione(com, ora);
                                        else mySim.impostaCondizioneAttivazione(com, ev);
                                        
					Programma p = (Programma) programmiList.getSelectedValue();
					ArrayList<ComandoProgramma> comandi = p.getComandi();
					this.aggiornaElencoComandi(comandi);
                                        com.salvaComando();
                                    }
                                    else { // ALternativamente: se viene lanciata una eccezione
					JOptionPane.showMessageDialog(this, "Non puoi aggiungere ad un comando di un programma, lo stesso programma", "Errore", JOptionPane.ERROR_MESSAGE);
                                    }
				} else { // ALternativamente: se viene lanciata una eccezione
					JOptionPane.showMessageDialog(this, "Nome non disponibile ", "Errore", JOptionPane.ERROR_MESSAGE);
				}
			} else {
				JOptionPane.showMessageDialog(this, "Parametri non validi", "Errore", JOptionPane.ERROR_MESSAGE);
			}
		}
    }//GEN-LAST:event_modificaComandoButtonActionPerformed

    private void importaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importaButtonActionPerformed
		/* @MODELINTERACTION qui parte tutto lo UC "Importare"
		 * Per prima cosa dobbiamo invocare l'operazione "ottieniElementiImportabili"
		 * ma per farlo ci serve sapere l'utente corrente.
		 * La view invoca dunque il seguente metodo sull'oggetto Scenario:
		 * - getAutore(): UserInfo
		 */
		// @EXAMPLE T2 & T3:
		UserInfo uInfo =mySim.getScenario().getInfoScenario().getAutore();

		/* @OPERATIONottieniScenariDiSimulazione
		 */
		// @EXAMPLES T2/T3:
		// ArrayList<InfoScenario> scenari = BackYardCtrl.ottieniElencoScenari(uInfo);
		 ArrayList<InfoScenario> scenari = null;
                try {
                    scenari = BackYardApplicationController.getAppController().OttieniScenariDiSimulazione(uInfo);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Impossibile Connettersi al DB", "Errore", JOptionPane.ERROR_MESSAGE);                    
                }

		// Mostra una finestra in cui scegliere lo scenario da cui importare (l'utente può premere Cancel)
		DefaultListModel<InfoScenario> lm = new DefaultListModel<>();
		for (InfoScenario sc : scenari) {
			lm.addElement(sc);
		}

		SceltaScenarioDialog dia = new SceltaScenarioDialog(this.owner);
		dia.setScenari(lm);
		dia.setVisible(true);

		if (dia.getValue() == JOptionPane.OK_OPTION) // L'utente ha premuto Ok
		{
			// Ottieni lo scenario prescelto
			InfoScenario daScenario = (InfoScenario) dia.getSelectedObject();

			/* @OPERATIONottieniElementiImportabili
			 * Attenzione: nella GUI il contesto viene mantenuto tramite due variabili
			 * di istanza
			 * 1) "contesto" (di tipo Contesto), che è uguale o all'Alloggio dello Scenario, o a uno
			 * dei Dispositivi, o a null se l'utente sta visualizzando i dispositivi ma 
			 * non ce n'è ancora nessuno.
			 * 2) "nomeContesto" (di tipo String), che è "alloggio" o "dispositivo" a seconda del tab
			 * selezionato.
			 * L'esempio qui di seguito usa la (1) ma, in base all'implementazione fatta di 
			 * ottieniElementiImportabili, si può scegliere di usare la (2)
			 */
			// @EXAMPLES T2/T3	
			// ArrayList<Importabile> elenco = BackYardCtrl.ottieniElementiImportabili(daScenario, nomeContesto);
			ArrayList<Importabile> elenco = null; //= BackYardApplicationController.getAppController().ottieniElementiImportabili(daScenario, contesto);

			// Mostra una finestra in cui scegliere l'elemento da importare (l'utente può premere Cancel)
			DefaultListModel<Importabile> implm = new DefaultListModel<>();
			for (Importabile imp : elenco) {
				implm.addElement(imp);
			}

			SceltaImportabileDialog impdia = new SceltaImportabileDialog(this.owner);
			impdia.setImportabili(implm);
			impdia.setVisible(true);

			if (impdia.getValue() == JOptionPane.OK_OPTION) // L'utente ha premuto Ok
			{
				//Ottieni l'elemento prescelto:
				Importabile imp = (Importabile) impdia.getSelectedObject();

				/* @OPERATIONimporta
				 * in base a come si è gestito il caso di import non possibile, bisogna o catturare
				 * l'eccezione o verificare il valore restituito dall'operazione				
				 */
				// @EXAMPLES T2/T3	
				// boolean importato = BackYardCtrl.importa(imp, nomeContesto);
				boolean importato= true; //= BackYardApplicationController.getAppController().importa(daScenario, myScenario, imp);

				if (importato) // Alternativamente: se NON viene lanciata alcuna eccezione
				{
					// se il contesto è l'alloggio, aggiorna l'elenco dei piani
					if (nomeContesto.equals("alloggio")) {
						/* @MODELINTERACTION la vista richiama sull'oggetto ScenarioSimulazione
						 * il seguente metodo necessario al proprio aggiornamento 
						 * - getPiani(): ArrayList<Piano>
						 */
						//ArrayList<Piano> piani = myScenario.getPiani();
						//this.aggiornaElencoPiani(piani);
					} else { // se il contesto è il dispositivo, aggiorna l'elenco dei dispositivi
						/* @MODELINTERACTION la vista richiama sull'oggetto ScenarioSimulazione
						 * il seguente metodo necessario al proprio aggiornamento 
						 * - getDispositivi(): ArrayList<DispositivoIntelligente>
						 */
						//ArrayList<DispositivoIntelligente> disp = myScenario.getDispositivi();
						//this.aggiornaElencoDispositivi(disp);
					}

				} else { // ALternativamente: se viene lanciata una eccezione
					JOptionPane.showMessageDialog(this, "Elemento non importabile", "Errore", JOptionPane.ERROR_MESSAGE);
				}

			}
		}
    }//GEN-LAST:event_importaButtonActionPerformed

    private void simulazioneTabbedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_simulazioneTabbedStateChanged
		/* Questa operazione imposta la variabile contesto 
		 * all'Alloggio o al DispositivoIntelligente attualmente selezionato.
		 * ATTENZIONE che il contesto potrebbe anche essere null (se sono
		 * sul tab "Dispositivi" ma non c'è alcun dispositivo da selezionare)
		 */
		int tabIndex = ((JTabbedPane) evt.getSource()).getSelectedIndex();
		String tabName = ((JTabbedPane) evt.getSource()).getTitleAt(tabIndex);
		/*if (tabName.equals("Planimetria")) {
			contesto = planimetria;
			nomeContesto = "alloggio";
		} else {
			int dispIndex = this.dispositiviCombo.getSelectedIndex();
			if (dispIndex < 0) {
				contesto = null;
			} else {
				contesto = (DispositivoIntelligente) this.dispositiviCombo.getSelectedItem();
			}
			nomeContesto = "dispositivo";
		}*/
    }//GEN-LAST:event_simulazioneTabbedStateChanged

    private void risorseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_risorseButtonActionPerformed
		GestioneRisorseDialog dia = new GestioneRisorseDialog(this.owner);
		//dia.setup(myScenario, contesto, nomeContesto);
		dia.setVisible(true);
    }//GEN-LAST:event_risorseButtonActionPerformed

    private void attivaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attivaButtonActionPerformed
        // TODO add your handling code here:
        Programma p = (Programma) programmiList.getSelectedValue();
        if(!p.isGenerico()) this.mySim.aggiungiASimulazione(p);
        ArrayList<Programma> prog = mySim.ottieniElencoProgrammi();
	this.aggiornaElencoProgrammi(prog);;
    }//GEN-LAST:event_attivaButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attivaButton;
    private javax.swing.JPanel blankPanel;
    private javax.swing.JButton chiudiButton;
    private javax.swing.JList comandiList;
    private javax.swing.JLabel datiLabel;
    private javax.swing.JPanel editProgrammaP;
    private javax.swing.JPanel elencoProgrammi;
    private javax.swing.JButton eliminaPianoButton;
    private javax.swing.JButton eliminaStanzaButton;
    private javax.swing.JButton importaButton;
    private javax.swing.JPanel iscrizioniPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton modificaComandoButton;
    private javax.swing.JButton modificaDatiButton;
    private javax.swing.JButton nuovaStanzaButton;
    private javax.swing.JButton nuovoPianoButton;
    private javax.swing.JPanel programmaP;
    private javax.swing.JPanel programmaPanel;
    private javax.swing.JList programmiList;
    private javax.swing.JButton risorseButton;
    private javax.swing.JButton salvaButton;
    private javax.swing.JPanel scenarioSP;
    private javax.swing.JTabbedPane simulazioneTabbed;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

	private void aggiornaElencoProgrammi(ArrayList<Programma> programmi) {
		this.progListModel.removeAllElements();
		for (Programma p : programmi) {
			this.progListModel.addElement(p);
		}

		this.programmiList.clearSelection();
	}

	private void aggiornaElencoComandi(ArrayList<ComandoProgramma> comandi) {
		this.comListModel.removeAllElements();
		for (ComandoProgramma com : comandi) {
			this.comListModel.addElement(com);
		}

		this.comandiList.clearSelection();
	}

	private void aggiornaElencoDispositivi(ArrayList<DispositivoIntelligente> dispositivi) {
		this.dispositiviComboModel.removeAllElements();
		for (DispositivoIntelligente di : dispositivi) {
			this.dispositiviComboModel.addElement(di);
		}
/*
		if (this.dispositiviComboModel.getSize() > 0) {
			this.dispositiviCombo.setSelectedIndex(0);
			if (contesto != planimetria) {
				contesto = (DispositivoIntelligente) dispositiviCombo.getSelectedItem();
			}
		} else {
			if (contesto != planimetria) {
				contesto = null;
			}
		}*/
	}
}
